name: BackEnd pipeline

on:
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Build and test with Gradle Wrapper
    - run: cd BackEnd
    - run: ./gradlew build
    - run: ./gradlew bootTestRun
