name: Automated code testing

on:
  pull_request:
    branches:
      - main
      
jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Build
      run: cd BackEnd && ./gradlew build

    - name: Run tests
      run: cd BackEnd && ./gradlew test

  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: cd FrontEnd && npm ci
      - run: cd FrontEnd && npm run build
      - run: cd FrontEnd && npm test
